services:
  samba-coordinator:
    image: dperson/samba:latest
    container_name: samba-coordinator
    ports:
      - "34451:445"
    volumes:
      - /mnt/paragon_storage/001:/mnt/disk1
    environment:
      - TZ=Europe/Moscow
    command: >
      -u "john;qQp9BA3CTfctG6iZWr7jSPHdFR"
      -s "001;/mnt/disk1;yes;no;no;john"
    restart: unless-stopped